spring:
  datasource:
    url: jdbc:mysql://database-1.cn4s886aafld.us-east-1.rds.amazonaws.com:3306/kotrip
    username: master
    password: sangyunpark99

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.jdbc: DEBUG