spring:
  datasource:
    url: jdbc:mysql://database-1.cn4s886aafld.us-east-1.rds.amazonaws.com:3306/kotrip
    username: master
    password: sangyunpark99
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.springframework.jdbc: DEBUG



API-KEY:
  clientId: ncxf9y01px
  clientSecret : LvhEc7kuJJ36IVotDQXQ8v1tjKGr8pbBZ9vVYYyM