# Test(7) : ec2 내에서 계정과 비밀번호 저장(git config --global credential.helper store)

name: kotrip github-action

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Github kotrip-backend repo 불러오기
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.USER_TOKEN }}
          submodules: true


      - name: SSH로 kotrip-backend EC2에 접속하기
        # https://github.com/marketplace/actions/ssh-remote-commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          # Please login as the user "ubuntu" rather than the user "***"
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/kotrip-backend
            git pull origin main
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
